config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'categories#index'

  get '/signup/judge_token_j' => 'users#secret'
  post '/signup/judge/l_step' => 'users#new_judge'
  post '/users/judge' => 'users#create_judge'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'

  get '/films/:id/reviews/new' => 'reviews#new'
  post '/films/:id/reviews' => 'reviews#create'
  get '/films/:id/reviews/edit' => 'reviews#edit'
  post '/films/:id/reviews/edit' => 'reviews#edit'

  put '/reviews/:id/edit' => 'reviews#edit'
  delete '/reviews/:id' => 'reviews#destroy'

  get '/reviews/:id/comments/new' => 'comments#new'
  post '/reviews/:id/comments' => 'comments#create'
  get '/films/reviews/:id/comments/:id/edit' => 'comments#edit'
  patch '/reviews/:id/comments/:id/update' => 'comments#update'
  delete '/comments/:id' => 'comments#destroy'

  get '/films/:id/ratings/new' => 'ratings#new', as: :film_rating
  post '/films/:id/ratings/new' => 'ratings#create'
  post '/films/:id/live' => 'films#live'

  get '/tokens/gen' => 'tokens#new'
  post '/tokens' => 'tokens#create'
  get '/tokens' => 'tokens#show'

  get '/dashboard/users' => 'dashboard#users'
  post '/dashboard' => 'dashboard#make_judge'
  delete '/dashboard' => 'dashboard#destroy_judge'

  get '/dashboard' => 'dashboard#index'
  get '/dashboard/categories' => 'dashboard#categories'
  get '/dashboard/categories/:id' => 'dashboard#category_films'
  post '/dashboard/categories' => 'dashboard#category_winner'

  get '/comments/flagged' => 'comments#flagged'
  delete '/comments' => 'comments#destroy'

  resources :categories, only: [:index, :show]
  resources :films, only: [:index, :show]
  resources :users, only: [:index, :new, :create, :show]
  resources :users do
    collection do
      get :judges

  end
end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :films

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  validates :body, presence: true
end

app/models/film.rb
class Film < ActiveRecord::Base
  belongs_to :category
  has_many :ratings
  has_many :reviews

  validates :name, :description, presence: true

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
    where("description ILIKE ?", "%#{search}%")
  end

  def user_avg
    if self.ratings.length >= 1
      users_ratings = self.ratings.select{ |rating| !rating.user.judge }
     ((users_ratings.map{ |rating| rating.value }.reduce(:+).to_f ) / ( users_ratings.length ).to_f).round(2)
    end
  end

  def judge_avg
    if self.ratings.length >= 1
      judge_ratings = self.ratings.select{ |rating| rating.user.judge }
     ((judge_ratings.map{ |rating| rating.value }.reduce(:+).to_f ) / ( judge_ratings.length ).to_f).round(2)
    end
  end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :film

  validates :value, presence: true
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :film
  belongs_to :user
  has_many :comments

  validates :title, :body, presence: true
end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :comments
  has_many :ratings
  has_secure_password

  validates :first_name, :last_name, presence: true
  validates :email, presence: true, format: { with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }, uniqueness: true
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include TokensHelper
  include CategoriesHelper

  def index
    if !logged_in? || ( logged_in? && !current_user.organizer )
      redirect_to root_path
    end
  end

  def users
    if logged_in? && current_user.organizer
      @users = User.order( last_name: :ASC )
    else
      redirect_to root_path
    end
  end

  def make_judge
    if logged_in? && current_user.organizer
      user = User.find_by( id: params[ :dashboard_judge ][ :user_id ] )
      if user
        if !Token.where( active: true ).empty?
          token = Token.where( active: true ).sample
          user.update_attributes( judge: true, judge_token: token.token )
          token.update_attributes( active: false )
          redirect_to '/dashboard/users'
        else
          Token.create( token: generate_token, active: false )
          user.update_attributes( judge: true, judge_token: Token.first.token )
          redirect_to '/dashboard/users'
        end
      end
    else
      redirect_to root_path
    end
  end

  def destroy_judge
    if logged_in? && current_user.organizer
      user = User.find_by( id: params[ :dashboard_judge ][ :user_id ] )
      user.update_attributes( judge: false, judge_token: nil )
      redirect_to '/dashboard/users'
    else
      redirect_to root_path
    end
  end

  def categories
    if logged_in? && current_user.organizer
      @categories = Category.all
    else
      redirect_to root_path
    end
  end

  def category_films
    if logged_in? && current_user.organizer
      @films = Film.where( category_id: params[ :id ] )
    else
      redirect_to root_path
    end
  end

  def category_winner
    if logged_in? && current_user.organizer
      @category = Category.find_by( id: params[ :winner ][ :category_id ] )
      @winner = determine_winner( @category )
      Film.find_by( name: @winner ).update_attributes( winner: true )
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def determine_winner( category )
    averages = {}

    category.films.each do | film |
      if ( film.user_avg != nil && !film.user_avg.nan? ) && ( film.judge_avg != nil && !film.judge_avg.nan? )
        judge_average = ( film.judge_avg * 1.25 ).round( 2 )
        averages[ film.name ] = ( film.user_avg + judge_average ).round( 2 )
      end
    end
    winner = averages.max_by { | film, avg | avg }[ 0 ]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def get_flagged_comments_amount
    comments = Comment.where( flag: true )
    comments.length
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
  def generate_token
    first = [ ('a'..'z'), ('A'..'Z') ].map { |i| i.to_a }.flatten
    @string = ( 0...50 ).map { first[ rand( first.length ) ] }.join
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def check_tokens( token )
    token = Token.find_by( token: token )

    if token && token.active == true
      return true
    else
      return false
    end
  end
end

app/views/dashboard/_delete_judge_form.html.erb
<%= form_for :dashboard_judge, url: '/dashboard', method: 'delete' do | f | %>
  <%= f.hidden_field :user_id, value: user.id %>
  <%= f.submit 'Revert To Regular User' %>
<% end %>

app/views/dashboard/_judge_form.html.erb
<%= form_for :dashboard_judge, url: '/dashboard' do | f | %>
  <%= f.hidden_field :user_id, value: user.id %>
  <%= f.submit 'Make Judge' %>
<% end %>

app/views/dashboard/categories.html.erb
<h1>Categories</h1>

<ul>
  <% @categories.each do | category | %>
    <li><a href="/dashboard/categories/<%= category.id %>"><%= category.name %></a></li>
  <% end %>
</ul>

app/views/dashboard/category_films.html.erb
<% if @films.empty? %>
  <h1>Sorry, this category has no films. Please go back <%= link_to 'Here', dashboard_categories_path %></h1>
<% else %>
  <h1>Films For Category: <%= Category.find_by( id: @films.first.category_id ).name.capitalize %></h1>

  <ul>
    <% @films.each do | film | %>
      <% if film.winner %>
        <li><%= film.name %> - Winner</li>
      <% else %>
        <li><%= film.name %></li>
      <% end %>
    <% end %>
  </ul>

  <% if !@films.any? { |film| film.winner } %>
    <%= form_for :winner, url:'/dashboard/categories' do | f | %>
      <%= f.hidden_field :category_id, value: @films.first.category_id %>
      <%= f.submit 'Calculate Winner' %>
    <% end %>
  <% end %>

  <% if !@films.any? { |film| film.live } %>
    <%= form_for :display_winner, url: "/films/#{ @films.find_by( winner: true ).id }/live" do | f | %>
      <%= f.hidden_field :film_id, value: @films.find_by( winner: true ).id %>
      <%= f.hidden_field :live, value: true %>
      <%= f.submit 'Show Winner Live' %>
    <% end %>
  <% else %>
    <%= form_for :display_winner, url: "/films/#{ @films.find_by( winner: true ).id }/live" do | f | %>
      <%= f.hidden_field :film_id, value: @films.find_by( winner: true ).id %>
      <%= f.hidden_field :live, value: false %>
      <%= f.submit 'Hide Winner Live' %>
    <% end %>
  <% end %>
<% end %>

app/views/dashboard/category_winner.html.erb
<h1>The winner is: <%= @winner %></h1>

app/views/dashboard/index.html.erb
<div class="notifications">
  <h3>Notifications</h3>
  <p>
    You have <%= link_to get_flagged_comments_amount, comments_flagged_path %> flagged comments for review
  </p>
</div>

<div class="tokens">
  <h3>Tokens</h3>
  <a href="/tokens/gen">Generate New Judge Token</a><br>
  <a href="/tokens">View All Active Tokens</a><br>
</div>

<div class="users">
  <h3>Users Portal</h3>
  <a href="/dashboard/users">View All Users</a><br>
</div>

<div class="categories">
  <h3>Categories</h3>
  <a href="/dashboard/categories">View All Categories</a>
</div>

app/views/dashboard/users.html.erb
<ul>
  <% @users.each do | user | %>
    <% if !user.organizer %>
      <li><%= user.last_name %>, <%= user.first_name %></li>
      <% if !user.judge %>
        <%= render template: '/dashboard/_judge_form', locals: { user: user } %>
      <% else %>
        <%= render template: '/dashboard/_delete_judge_form', locals: { user: user } %>
      <% end %>
    <% end %>
  <% end %>
</ul>