config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'categories#index'

  get '/signup/judge_token_j' => 'users#secret'
  post '/signup/judge/l_step' => 'users#new_judge'
  post '/users/judge' => 'users#create_judge'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'

  get '/films/:id/reviews/new' => 'reviews#new'
  post '/films/:id/reviews' => 'reviews#create'
  get '/films/:id/reviews/edit' => 'reviews#edit'
  post '/films/:id/reviews/edit' => 'reviews#edit'

  put '/reviews/:id/edit' => 'reviews#edit'
  delete '/reviews/:id' => 'reviews#destroy'

  get '/reviews/:id/comments/new' => 'comments#new'
  post '/reviews/:id/comments' => 'comments#create'
  get '/films/reviews/:id/comments/:id/edit' => 'comments#edit'
  patch '/reviews/:id/comments/:id/update' => 'comments#update'
  delete '/comments/:id' => 'comments#destroy'

  get '/films/:id/ratings/new' => 'ratings#new', as: :film_rating
  post '/films/:id/ratings/new' => 'ratings#create'
  post '/films/:id/live' => 'films#live'

  get '/tokens/gen' => 'tokens#new'
  post '/tokens' => 'tokens#create'
  get '/tokens' => 'tokens#show'

  get '/dashboard/users' => 'dashboard#users'
  post '/dashboard' => 'dashboard#make_judge'
  delete '/dashboard' => 'dashboard#destroy_judge'

  get '/dashboard' => 'dashboard#index'
  get '/dashboard/categories' => 'dashboard#categories'
  get '/dashboard/categories/:id' => 'dashboard#category_films'
  post '/dashboard/categories' => 'dashboard#category_winner'

  get '/comments/flagged' => 'comments#flagged'
  delete '/comments' => 'comments#destroy'

  resources :categories, only: [:index, :show]
  resources :films, only: [:index, :show]
  resources :users, only: [:index, :new, :create, :show]
  resources :users do
    collection do
      get :judges

  end
end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :films

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  validates :body, presence: true
end

app/models/film.rb
class Film < ActiveRecord::Base
  belongs_to :category
  has_many :ratings
  has_many :reviews

  validates :name, :description, presence: true

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
    where("description ILIKE ?", "%#{search}%")
  end

  def user_avg
    if self.ratings.length >= 1
      users_ratings = self.ratings.select{ |rating| !rating.user.judge }
     ((users_ratings.map{ |rating| rating.value }.reduce(:+).to_f ) / ( users_ratings.length ).to_f).round(2)
    end
  end

  def judge_avg
    if self.ratings.length >= 1
      judge_ratings = self.ratings.select{ |rating| rating.user.judge }
     ((judge_ratings.map{ |rating| rating.value }.reduce(:+).to_f ) / ( judge_ratings.length ).to_f).round(2)
    end
  end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :film

  validates :value, presence: true
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :film
  belongs_to :user
  has_many :comments

  validates :title, :body, presence: true
end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :comments
  has_many :ratings
  has_secure_password

  validates :first_name, :last_name, presence: true
  validates :email, presence: true, format: { with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }, uniqueness: true
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @found_film = Film.find_by(name: params[:search])
    if request.xhr?
      if @found_film != nil
        render template: '/films/_redirect', layout: false, locals: { film: @found_film }
      else
        render template: '/films/_not_found', layout: false
      end
    end
  end

  def show
    @film = Film.find(params[:id])
    @stars = @film.user_avg.round if @film.user_avg != nil
    @reviews = Review.where( film_id: @film.id )
  end

  def live
    film = Film.find_by( id: params[ :display_winner ][ :film_id ] )
    film.update_attributes( live_params)
    redirect_to film_path( film )
  end

  private
  def live_params
    params.require( :display_winner ).permit( :live )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  def new
  end

  def create
    @user = User.new(user_params)
    if user_params[ :password ] == user_params[ :password_confirmation ]
      if @user.save
        session[:user_id] = @user.id
        redirect_to categories_path
      else
        @errors = @user.errors.full_messages
        render template: '/users/new'
      end
    else
      @user.save
      @errors = @user.errors.full_messages
      render template: '/users/new'
    end
  end


  def show
    @user = User.find(params[:id])
  end


  def secret
  end

  def new_judge
    if check_tokens( params[:secret][:secret_key] )
      @token = params[:secret][:secret_key]
      render template: '/users/new_judge'
    else
      @error = 'Your token is either no longer valid or incorrect!'
      render template: '/users/secret'
    end
  end

  def create_judge
    token = params[ :user ][ :judge_token ]
    if check_tokens( token )
      @user = User.new( user_params )
      if @user.save
        @user.update_attributes( judge: true )
        update_token = Token.find_by( token: token )
        update_token.update_attributes( active: false )
        session[ :user_id ] = @user.id
        redirect_to root_path
      else
        @errors = @user.errors.full_messages
        render template: '/users/new_judge'
      end
    else
      redirect_to root_path
    end
  end

  def judges
    @judges=User.where(:judge => true)

  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :judge, :judge_token, :organizer)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def determine_winner( category )
    averages = {}

    category.films.each do | film |
      if ( film.user_avg != nil && !film.user_avg.nan? ) && ( film.judge_avg != nil && !film.judge_avg.nan? )
        judge_average = ( film.judge_avg * 1.25 ).round( 2 )
        averages[ film.name ] = ( film.user_avg + judge_average ).round( 2 )
      end
    end
    winner = averages.max_by { | film, avg | avg }[ 0 ]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def get_flagged_comments_amount
    comments = Comment.where( flag: true )
    comments.length
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
  def generate_token
    first = [ ('a'..'z'), ('A'..'Z') ].map { |i| i.to_a }.flatten
    @string = ( 0...50 ).map { first[ rand( first.length ) ] }.join
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def check_tokens( token )
    token = Token.find_by( token: token )

    if token && token.active == true
      return true
    else
      return false
    end
  end
end

app/views/films/_not_found.html.erb
No Film Found By That Name

app/views/films/_redirect.html.erb
/films/<%= film.id %>

app/views/films/show.html.erb
<div id="film_show">

<h1> <%= @film.name %> </h1>

<p>
  <% if @stars == nil %>
      &#9734;
  <% else %>
    <% @stars.times do %>
      &#11088;
    <% end %>
  <% end %>
</p>

<% if @film.live %>
  <p>
    Winner Of The <%= @film.category.name.capitalize %> Category
  </p>
<% end %>

<%= @film.description.scan(/[A-Za-z. 0-9]/).join() %>

<%= @film.cast %><br>

<%= @film.crew %><br>


<% if @film.ratings %>
<div id="ratings">
  <p>Average audience rating:<%= @film.user_avg %></p>
  <p>Average judge rating:<%= @film.judge_avg %></p>
<%end%>

<p>Rate this film:</p>

<% if logged_in? %>
  <%= form_for @film, method: :post, url: :film_rating do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :film_id, value: @film.id %>
  <%= f.select :ratings, [5, 4.5, 4, 3.5, 3, 2.5, 2, 1.5, 1], :prompt => 'Select One' %>

  <%=f.submit %>

  <%end%>
<% else %>
  <p id="signup">
    Please <a href="/signup">Signup</a> or <a href="/login">Login</a> to rate this film
  </p>
<% end %>
</div>
</div>
<div id="top_nav">
<% if logged_in? %>
<ul>
  <li><%= link_to 'create a new review', "/films/#{@film.id}/reviews/new" %>
<% end %>

<li><%= link_to 'back', "/categories/#{@film.category_id}"%></li>
</ul>
</div>
<div id="review_block">
<h2>Reviews for <%=@film.name %></h2>


<div id="review-container">
  <% @reviews.each do |review| %>
    <h3><%= review.title %> </h3>
    <h4> "<%= review.body %> "</h4>
    <p> left by: <%=review.user.first_name %> <%=review.user.last_name %>
      <% if review.user.judge %>
        <span id="judge">&#9733;<i>judge review</i></span>
      <%end%>
    </p>

    <div class="outside-comments-container">
      <% review.comments.each do |comment| %>
        <%= render template: '/comments/_all_comments', locals: { comment: comment, review: review } %>
      <% end %>

      <% if logged_in? %>
        <%= link_to 'create comment', "/reviews/#{review.id}/comments/new", class: 'new-comment' %>
      <% end %><br>
    </div>
  <% end %>



</div>



</div>

app/views/users/index.html.erb
<h1> Judges Index </h1>

<% if @judges %>
  <ul>
      <% @judges.each do |judge| %>
        <li><%= judge.first_name %> <%= judge.last_name %> </li>
      <% end %>
    </ul>
  <% end %>

app/views/users/new.html.erb
<div id="container">
<% if @errors %>
  <ul>
    <% @errors.each do | error | %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for :user, url: '/users' do | f | %>
  <%= f.text_field :first_name, placeholder: 'First Name' %><br>
  <%= f.text_field :last_name, placeholder: 'Last Name' %><br>
  <%= f.text_field :email, placeholder: 'Email' %><br>
  <%= f.password_field :password, placeholder: 'Password' %><br>
  <%= f.password_field :password_confirmation, placeholder: 'Confirm Password' %><br>
  <%= f.submit 'REGISTER' %>
<% end %>
</div>

app/views/users/new_judge.html.erb
<% if @errors %>
  <ul>
    <% @errors.each do | error | %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for :user, url: '/users/judge' do | f | %>
  <%= f.hidden_field :judge_token, value: @token %>
  <%= f.text_field :first_name, placeholder: 'First Name' %><br>
  <%= f.text_field :last_name, placeholder: 'Last Name' %><br>
  <%= f.text_field :email, placeholder: 'Email' %><br>
  <%= f.password_field :password, placeholder: 'Password' %><br>
  <%= f.password_field :password_confirmation, placeholder: 'Confirm Password' %><br>
  <%= f.submit 'Become A Judge' %>
<% end %>

app/views/users/secret.html.erb
<% if @error %>
  <p>
    <%= @error %>
  </p>
<% end %>

<%= form_for :secret, url: '/signup/judge/l_step' do | f | %>
  <%= f.text_field :secret_key, placeholder: 'Enter Judge Token' %><br>
  <%= f.submit 'Proceed To Sign Up' %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.first_name%> <%= @user.last_name %>'s Profile Page</h2>

<% if current_user.judge? == true %>
  <h2> Films I Have Rated </h2>
  <% current_user.ratings.each do |rating| %>
    <%= link_to rating.film, rating_path(@rating) %>
  <% end %>
<% end %>